/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FPR_audio_BeatzDecoder */

#ifndef _Included_Mpg123Decoder
#define _Included_Mpg123Decoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FPR_audio_BeatzDecoder
 * Method:    openFile
 * Signature: (Ljava/lang/String;)J
 */
jlong Java_FPR_audio_BeatzDecoder_openFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     FPR_audio_BeatzDecoder
 * Method:    readSamples
 * Signature: (J[SII)I
 */
jint Java_FPR_audio_BeatzDecoder_readSamples
  (JNIEnv *, jobject, jlong, jshortArray, jint, jint);

/*
 * Class:     FPR_audio_BeatzDecoder
 * Method:    flagBeats
 * Signature: (J[FI)I
 */
jint Java_FPR_audio_BeatzDecoder_flagBeats
  (JNIEnv *, jobject, jlong, jfloatArray, jint, jfloat);

/*
 * Class:     FPR_audio_BeatzDecoder
 * Method:    skipSamples
 * Signature: (JI)I
 */
jint Java_FPR_audio_BeatzDecoder_skipSamples
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     FPR_audio_BeatzDecoder
 * Method:    getNumChannels
 * Signature: (J)I
 */
jint Java_FPR_audio_BeatzDecoder_getNumChannels
  (JNIEnv *, jobject, jlong);

/*
 * Class:     FPR_audio_BeatzDecoder
 * Method:    getRate
 * Signature: (J)I
 */
jint Java_FPR_audio_BeatzDecoder_getRate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     FPR_audio_BeatzDecoder
 * Method:    getLength
 * Signature: (J)F
 */
jfloat Java_FPR_audio_BeatzDecoder_getLength
  (JNIEnv *, jobject, jlong);

/*
 * Class:     FPR_audio_BeatzDecoder
 * Method:    closeFile
 * Signature: (J)V
 */
void Java_FPR_audio_BeatzDecoder_closeFile
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
